'use client';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { Alert } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { listMyOrders } from '@/services/order-service';
import { createOrderSocket } from '@/services/order-socket';
import type { Order } from '@/types/order';
import { formatInr } from '@/utils/money';

type Group = 'active' | 'completed' | 'cancelled';
const groups: { value: Group; label: string }[] = [{ value: 'active', label: 'Active' }, { value: 'completed', label: 'Completed' }, { value: 'cancelled', label: 'Cancelled / rejected' }];
const badge: Record<string, string> = { PENDING: 'bg-amber-100 text-amber-800', ACCEPTED: 'bg-blue-100 text-blue-800', PREPARING: 'bg-violet-100 text-violet-800', READY: 'bg-green-100 text-green-800', COMPLETED: 'bg-stone-200 text-stone-700', REJECTED: 'bg-red-100 text-red-800', CANCELLED: 'bg-red-100 text-red-800' };
export function MyOrders() {
  const [group, setGroup] = useState<Group>('active'); const [orders, setOrders] = useState<Order[]>([]); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [search, setSearch] = useState(''); const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading'); const [live, setLive] = useState(false);
  const load = useCallback(async (silent = false) => { if (!silent) setState('loading'); try { const result = await listMyOrders({ group, page, limit: 20, ...(search.trim() ? { search: search.trim() } : {}) }); setOrders(result.orders); setPages(Math.max(1, result.pagination.totalPages)); setState('ready'); } catch { if (!silent) setState('error'); } }, [group, page, search]);
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [load]);
  useEffect(() => { const timer = window.setInterval(() => void load(true), 20_000); return () => window.clearInterval(timer); }, [load]);
  useEffect(() => { const socket = createOrderSocket(); const refresh = () => void load(true); socket.on('connect', () => { setLive(true); refresh(); }); socket.on('disconnect', () => setLive(false)); socket.on('connect_error', () => setLive(false)); socket.on('order:created', refresh); socket.on('order:status-changed', refresh); socket.on('order:payment-changed', refresh); socket.on('order:cancelled', refresh); return () => { socket.disconnect(); }; }, [load]);
  return <div className="mt-8 space-y-6"><div className="flex flex-col gap-4 rounded-3xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div role="tablist" aria-label="Order history sections" className="flex flex-wrap gap-2">{groups.map((item) => <button role="tab" aria-selected={group === item.value} key={item.value} onClick={() => { setGroup(item.value); setPage(1); }} className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${group === item.value ? 'bg-brand-orange-500 text-white' : 'bg-stone-100 text-stone-700'}`}>{item.label}</button>)}</div><span className={`rounded-full px-3 py-1 text-xs font-bold ${live ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800'}`}>{live ? 'Live updates connected' : 'Refreshing periodically'}</span></div><div className="flex gap-3"><input aria-label="Search my orders" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search order number or outlet" className="min-h-11 flex-1 rounded-xl border border-stone-300 px-4"/><Button variant="ghost" onClick={() => void load()}>Refresh</Button></div></div>
    {state === 'loading' ? <div role="status" className="rounded-3xl border bg-white p-10 text-center text-stone-500">Loading your orders…</div> : null}{state === 'error' ? <div><Alert>Your orders could not be loaded.</Alert><Button variant="ghost" className="mt-3" onClick={() => void load()}>Try again</Button></div> : null}{state === 'ready' && !orders.length ? <section className="rounded-3xl border border-dashed border-stone-300 bg-white p-10 text-center"><h2 className="text-xl font-bold">No {group} orders</h2><p className="mt-2 text-stone-500">{group === 'active' ? 'Your next confirmed order will appear here.' : 'Orders in this section will appear here.'}</p>{group === 'active' ? <Link href="/user" className="mt-5 inline-flex rounded-xl bg-brand-orange-500 px-5 py-3 font-semibold text-white">Explore outlets</Link> : null}</section> : null}
    {state === 'ready' && orders.length ? <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{orders.map((order) => <Link key={order.id} href={`/user/orders/${order.id}`} className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm transition hover:border-orange-300 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-brand-orange-600">{order.orderNumber}</p><h2 className="mt-2 text-lg font-bold">{order.hotelName}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${badge[order.status]}`}>{order.status}</span></div><p className="mt-4 text-sm text-stone-500">{order.items.reduce((sum, item) => sum + item.quantity, 0)} items · {order.deliveryType === 'PICKUP' ? 'Pickup' : 'Delivery'} · {order.orderType === 'PREORDER' ? 'Pre-order' : 'Order now'}</p><div className="mt-5 flex items-end justify-between"><span className="text-xs text-stone-500">{new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(order.createdAt))}</span><strong>{formatInr(order.totalAmountPaise)}</strong></div></Link>)}</section> : null}{pages > 1 ? <div className="flex items-center justify-center gap-3"><Button variant="ghost" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</Button><span className="text-sm">Page {page} of {pages}</span><Button variant="ghost" disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>Next</Button></div> : null}
  </div>;
}
