'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { Alert } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { ApiClientError } from '@/services/api-client';
import { cancelOrder, getOrder } from '@/services/order-service';
import { createOrderSocket } from '@/services/order-socket';
import type { Order } from '@/types/order';
import { formatInr } from '@/utils/money';
import { OrderPriceSummary } from './order-summary';

export function OrderDetail({ id }: { id: string }) {
  const [order, setOrder] = useState<Order | null>(null); const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading'); const [message, setMessage] = useState(''); const [live, setLive] = useState(false); const [busy, setBusy] = useState(false);
  const load = useCallback(async (silent = false) => { if (!silent) setStatus('loading'); try { const result = await getOrder(id); setOrder(result.order); setStatus('ready'); } catch (error) { if (!silent) { setMessage(error instanceof ApiClientError ? error.message : 'Order details could not be loaded.'); setStatus('error'); } } }, [id]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const timer = window.setInterval(() => void load(true), 20_000); return () => window.clearInterval(timer); }, [load]);
  useEffect(() => { const socket = createOrderSocket(); const refresh = () => void load(true); socket.on('connect', () => { setLive(true); socket.emit('order:subscribe', id, () => refresh()); }); socket.on('disconnect', () => setLive(false)); socket.on('connect_error', () => setLive(false)); socket.on('order:status-changed', refresh); socket.on('order:payment-changed', refresh); socket.on('order:cancelled', refresh); return () => { socket.emit('order:unsubscribe', id); socket.disconnect(); }; }, [id, load]);
  async function cancel() { if (!order || busy || !window.confirm('Cancel this pending order? This cannot be undone.')) return; setBusy(true); setMessage(''); try { setOrder((await cancelOrder(order.id)).order); } catch (error) { setMessage(error instanceof ApiClientError ? error.message : 'The order could not be cancelled.'); await load(true); } finally { setBusy(false); } }
  if (status === 'loading') return <div role="status" className="mt-8 rounded-3xl border bg-white p-10 text-center text-stone-500">Loading your order…</div>;
  if (status === 'error' || !order) return <div className="mt-8"><Alert>{message}</Alert><Button variant="ghost" className="mt-4" onClick={() => void load()}>Try again</Button></div>;
  const scheduled = order.scheduledAt ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(order.scheduledAt)) : null;
  const progress = ['PENDING', 'ACCEPTED', 'PREPARING', 'READY', 'COMPLETED']; const current = progress.indexOf(order.status);
  return <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-6">{message ? <Alert>{message}</Alert> : null}<section className="rounded-3xl border border-green-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-green-700">Order number</p><h2 className="mt-2 text-3xl font-bold">{order.orderNumber}</h2><p className="mt-2 text-stone-600">Placed {new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(order.createdAt))}</p></div><div className="text-right"><span className="rounded-full bg-orange-100 px-4 py-2 text-sm font-bold text-orange-800">{order.status}</span><p className={`mt-3 text-xs font-semibold ${live ? 'text-green-700' : 'text-amber-700'}`}>{live ? 'Live updates connected' : 'Refreshing periodically'}</p></div></div></section>
    <section className="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Order progress</h2>{order.status === 'CANCELLED' || order.status === 'REJECTED' ? <div className="mt-4 rounded-2xl bg-red-50 p-4 font-semibold text-red-800">This order was {order.status.toLowerCase()}.</div> : <ol className="mt-6 grid gap-3 sm:grid-cols-5">{progress.map((step, index) => <li key={step} className={`rounded-xl border p-3 text-center text-xs font-bold ${index <= current ? 'border-green-300 bg-green-50 text-green-800' : 'border-stone-200 text-stone-400'}`}><span className="mx-auto mb-2 grid size-6 place-items-center rounded-full bg-current/10">{index < current ? '✓' : index + 1}</span>{step}</li>)}</ol>}{order.statusHistory?.length ? <ol className="mt-6 space-y-3 border-l-2 border-orange-200 pl-4">{order.statusHistory.map((entry) => <li key={entry.id}><strong className="text-sm">{entry.toStatus}</strong><p className="text-xs text-stone-500">{new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(entry.createdAt))}</p></li>)}</ol> : null}</section>
    <section className="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Items from {order.hotelName}</h2><div className="mt-5 divide-y divide-stone-200">{order.items.map((item) => <article key={item.id} className="flex justify-between gap-4 py-4 first:pt-0"><div><h3 className="font-semibold">{item.quantity} × {item.itemName}</h3><p className="mt-1 text-sm text-stone-500">{formatInr(item.pricePaise)} each · {item.veg ? 'Vegetarian' : 'Non-vegetarian'}</p></div><strong>{formatInr(item.itemTotalPaise)}</strong></article>)}</div></section>
    <section className="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Receiving details</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><div><dt className="text-xs uppercase tracking-wide text-stone-500">Order timing</dt><dd className="mt-1 font-semibold">{order.orderType === 'INSTANT' ? 'As soon as possible' : scheduled}</dd></div><div><dt className="text-xs uppercase tracking-wide text-stone-500">Receiving method</dt><dd className="mt-1 font-semibold">{order.deliveryType === 'PICKUP' ? 'Pick up at outlet' : 'Campus delivery'}</dd></div>{order.deliveryAddress ? <div className="sm:col-span-2"><dt className="text-xs uppercase tracking-wide text-stone-500">Delivery address</dt><dd className="mt-1">{order.deliveryAddress}</dd></div> : null}<div><dt className="text-xs uppercase tracking-wide text-stone-500">Contact</dt><dd className="mt-1">{order.userName}<br />{order.userPhone}</dd></div><div><dt className="text-xs uppercase tracking-wide text-stone-500">Payment</dt><dd className="mt-1">Cash · {order.paymentStatus}</dd></div></dl></section></div>
    <aside className="h-fit rounded-3xl border border-stone-200 bg-white p-6 shadow-sm lg:sticky lg:top-24"><h2 className="text-xl font-bold">Order total</h2><OrderPriceSummary totals={{ itemsTotalPaise: order.subtotalPaise, deliveryChargePaise: order.deliveryChargePaise, platformFeePaise: order.platformFeePaise, grandTotalPaise: order.totalAmountPaise }} />{order.status === 'PENDING' ? <Button variant="ghost" disabled={busy} className="mt-6 w-full text-red-700" onClick={() => void cancel()}>{busy ? 'Cancelling…' : 'Cancel order'}</Button> : null}<Link href="/user/orders" className="mt-3 block rounded-xl border border-stone-200 px-5 py-3 text-center text-sm font-semibold">Back to My Orders</Link><Link href="/user" className="mt-3 block text-center text-sm font-semibold text-stone-600">Continue browsing</Link></aside></div>;
}
