'use client';

import { useCallback, useEffect, useState } from 'react';
import { Alert } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { ApiClientError } from '@/services/api-client';
import { changeSellerOrderStatus, getSellerOrder, getSellerOrderSummary, listSellerOrders, markSellerOrderPaid } from '@/services/order-service';
import { createOrderSocket } from '@/services/order-socket';
import type { Order, OrderStatus, SellerOrderSummary } from '@/types/order';
import { formatInr } from '@/utils/money';
import { OrderPriceSummary } from './order-summary';

const statuses: OrderStatus[] = ['PENDING', 'ACCEPTED', 'PREPARING', 'READY', 'COMPLETED', 'REJECTED', 'CANCELLED'];
const nextStatus: Partial<Record<OrderStatus, OrderStatus>> = { PENDING: 'ACCEPTED', ACCEPTED: 'PREPARING', PREPARING: 'READY', READY: 'COMPLETED' };
const actionLabels: Partial<Record<OrderStatus, string>> = { ACCEPTED: 'Accept order', PREPARING: 'Start preparing', READY: 'Mark ready', COMPLETED: 'Complete order' };
const badge: Record<OrderStatus, string> = { PENDING: 'bg-amber-100 text-amber-800', ACCEPTED: 'bg-blue-100 text-blue-800', PREPARING: 'bg-violet-100 text-violet-800', READY: 'bg-green-100 text-green-800', COMPLETED: 'bg-stone-200 text-stone-700', REJECTED: 'bg-red-100 text-red-800', CANCELLED: 'bg-red-100 text-red-800' };
const initialSummary: SellerOrderSummary = { statusCounts: { PENDING: 0, ACCEPTED: 0, PREPARING: 0, READY: 0, COMPLETED: 0, REJECTED: 0, CANCELLED: 0 }, todayOrders: 0, todaySalesPaise: 0, todayCompletedOrders: 0, businessDate: '' };
const dateTime = (value: string) => new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));

export function SellerOrderWorkspace() {
  const [orders, setOrders] = useState<Order[]>([]); const [summary, setSummary] = useState(initialSummary);
  const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading'); const [status, setStatus] = useState<OrderStatus | ''>('');
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [total, setTotal] = useState(0);
  const [selected, setSelected] = useState<Order | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState('');
  const load = useCallback(async (silent = false) => { if (!silent) setState('loading'); try { const [queue, metrics] = await Promise.all([listSellerOrders({ page, limit: 20, ...(status ? { status } : {}), ...(search.trim() ? { search: search.trim() } : {}) }), getSellerOrderSummary()]); setOrders(queue.orders); setPages(Math.max(1, queue.pagination.totalPages)); setTotal(queue.pagination.total); setSummary(metrics); setState('ready'); } catch { if (!silent) setState('error'); } }, [page, status, search]);
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [load]);
  useEffect(() => { const timer = window.setInterval(() => void load(true), 15_000); return () => window.clearInterval(timer); }, [load]);
  useEffect(() => { const socket = createOrderSocket(); const refresh = () => void load(true); socket.on('connect', refresh); socket.on('order:created', refresh); socket.on('order:status-changed', refresh); socket.on('order:payment-changed', refresh); socket.on('order:cancelled', refresh); return () => { socket.disconnect(); }; }, [load]);
  async function open(order: Order) { setDetailLoading(true); setFeedback(''); try { setSelected((await getSellerOrder(order.id)).order); } catch { setFeedback('Order details could not be loaded.'); } finally { setDetailLoading(false); } }
  function sync(updated: Order) { setSelected(updated); setOrders((current) => current.map((order) => order.id === updated.id ? updated : order)); void load(true); }
  async function transition(target: OrderStatus) { if (!selected || busy) return; if ((target === 'REJECTED' || target === 'COMPLETED') && !window.confirm(target === 'REJECTED' ? 'Reject this pending order? This cannot be undone.' : 'Complete this paid order?')) return; setBusy(true); setFeedback(''); try { sync((await changeSellerOrderStatus(selected.id, target)).order); } catch (error) { setFeedback(error instanceof ApiClientError ? error.message : 'Order status could not be changed.'); } finally { setBusy(false); } }
  async function markPaid() { if (!selected || busy || !window.confirm('Confirm that you collected the cash payment?')) return; setBusy(true); setFeedback(''); try { sync((await markSellerOrderPaid(selected.id)).order); } catch (error) { setFeedback(error instanceof ApiClientError ? error.message : 'Payment could not be updated.'); } finally { setBusy(false); } }
  return <div className="mt-8 space-y-6">
    <section aria-label="Today order metrics" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      ['New orders', summary.statusCounts.PENDING], ['In progress', summary.statusCounts.ACCEPTED + summary.statusCounts.PREPARING], ['Ready', summary.statusCounts.READY], ["Today's paid sales", formatInr(summary.todaySalesPaise)],
    ].map(([label, value]) => <article key={label} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-stone-500">{label}</p><p className="mt-2 text-3xl font-bold text-stone-950">{value}</p></article>)}</section>
    <section className="rounded-3xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><div className="grid gap-3 md:grid-cols-[1fr_220px_auto]"><input aria-label="Search orders" value={search} onChange={(event) => { setPage(1); setSearch(event.target.value); }} placeholder="Order number, student or phone" className="min-h-12 rounded-xl border border-stone-300 px-4"/><select aria-label="Order status" value={status} onChange={(event) => { setPage(1); setStatus(event.target.value as OrderStatus | ''); }} className="min-h-12 rounded-xl border border-stone-300 bg-white px-4"><option value="">All statuses</option>{statuses.map((value) => <option key={value}>{value}</option>)}</select><Button variant="ghost" onClick={() => void load()}>Refresh</Button></div><p className="mt-3 text-xs text-stone-500">Automatically refreshes every 15 seconds · {total} matching orders</p></section>
    {state === 'loading' ? <div role="status" className="rounded-3xl border bg-white p-10 text-center text-stone-500">Loading the order queue…</div> : null}
    {state === 'error' ? <div><Alert>Orders could not be loaded.</Alert><Button variant="ghost" className="mt-3" onClick={() => void load()}>Try again</Button></div> : null}
    {state === 'ready' && !orders.length ? <section className="rounded-3xl border border-dashed border-stone-300 bg-white p-10 text-center"><h2 className="text-xl font-bold">No matching orders</h2><p className="mt-2 text-stone-500">New student orders will appear here automatically.</p></section> : null}
    {state === 'ready' && orders.length ? <section aria-label="Seller orders" className="grid gap-4 lg:grid-cols-2">{orders.map((order) => <button type="button" key={order.id} onClick={() => void open(order)} className="rounded-3xl border border-stone-200 bg-white p-5 text-left shadow-sm transition hover:border-orange-300 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-brand-orange-600">{order.orderNumber}</p><h2 className="mt-2 text-lg font-bold">{order.userName}</h2><p className="mt-1 text-sm text-stone-500">{order.items.reduce((sum, item) => sum + item.quantity, 0)} items · {order.deliveryType === 'PICKUP' ? 'Pickup' : 'Delivery'} · {order.orderType === 'INSTANT' ? 'Now' : 'Pre-order'}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${badge[order.status]}`}>{order.status}</span></div><div className="mt-5 flex items-end justify-between"><span className="text-xs text-stone-500">{dateTime(order.createdAt)}</span><strong className="text-lg">{formatInr(order.totalAmountPaise)}</strong></div></button>)}</section> : null}
    {pages > 1 ? <div className="flex items-center justify-center gap-4"><Button variant="ghost" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</Button><span className="text-sm">Page {page} of {pages}</span><Button variant="ghost" disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>Next</Button></div> : null}
    {detailLoading ? <p role="status" className="text-center text-sm text-stone-500">Opening order…</p> : null}{feedback ? <Alert>{feedback}</Alert> : null}{selected ? <OrderPanel order={selected} busy={busy} close={() => setSelected(null)} transition={transition} markPaid={markPaid} /> : null}
  </div>;
}

function OrderPanel({ order, busy, close, transition, markPaid }: { order: Order; busy: boolean; close: () => void; transition: (status: OrderStatus) => Promise<void>; markPaid: () => Promise<void> }) {
  const target = nextStatus[order.status]; const scheduled = order.scheduledAt ? dateTime(order.scheduledAt) : null;
  return <section aria-labelledby="seller-order-detail" className="rounded-3xl border-2 border-orange-200 bg-white p-5 shadow-lg sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-brand-orange-600">{order.orderNumber}</p><h2 id="seller-order-detail" className="mt-2 text-2xl font-bold">Order from {order.userName}</h2><p className="mt-1 text-sm text-stone-500">Placed {dateTime(order.createdAt)}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${badge[order.status]}`}>{order.status}</span><Button variant="ghost" onClick={close}>Close</Button></div></div>
    <div className="mt-7 grid gap-7 lg:grid-cols-[1fr_340px]"><div className="space-y-6"><section><h3 className="font-bold">Customer and receiving</h3><dl className="mt-3 grid gap-4 rounded-2xl bg-stone-50 p-4 sm:grid-cols-2"><div><dt className="text-xs uppercase text-stone-500">Contact</dt><dd className="mt-1 font-semibold">{order.userName}<br/><a href={`tel:${order.userPhone}`} className="text-brand-orange-600">{order.userPhone}</a></dd></div><div><dt className="text-xs uppercase text-stone-500">Method</dt><dd className="mt-1 font-semibold">{order.deliveryType === 'PICKUP' ? 'Pickup at outlet' : 'Campus delivery'}<br/>{order.orderType === 'PREORDER' ? scheduled : 'As soon as possible'}</dd></div>{order.deliveryAddress ? <div className="sm:col-span-2"><dt className="text-xs uppercase text-stone-500">Address</dt><dd className="mt-1">{order.deliveryAddress}</dd></div> : null}</dl></section><section><h3 className="font-bold">Items</h3><div className="mt-3 divide-y divide-stone-200 rounded-2xl border border-stone-200 px-4">{order.items.map((item) => <div key={item.id} className="flex justify-between gap-3 py-4"><div><strong>{item.quantity} × {item.itemName}</strong><p className="text-xs text-stone-500">{item.veg ? 'Vegetarian' : 'Non-vegetarian'} · {formatInr(item.pricePaise)} each</p></div><strong>{formatInr(item.itemTotalPaise)}</strong></div>)}</div></section>{order.statusHistory?.length ? <section><h3 className="font-bold">Status history</h3><ol className="mt-3 space-y-3 border-l-2 border-orange-200 pl-4">{order.statusHistory.map((entry) => <li key={entry.id}><strong className="text-sm">{entry.toStatus}</strong><p className="text-xs text-stone-500">{dateTime(entry.createdAt)}</p></li>)}</ol></section> : null}</div>
      <aside><div className="rounded-2xl border border-stone-200 p-5"><h3 className="font-bold">Payment and total</h3><p className={`mt-3 inline-flex rounded-full px-3 py-1 text-xs font-bold ${order.paymentStatus === 'PAID' ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800'}`}>CASH · {order.paymentStatus}</p><OrderPriceSummary totals={{ itemsTotalPaise: order.subtotalPaise, deliveryChargePaise: order.deliveryChargePaise, platformFeePaise: order.platformFeePaise, grandTotalPaise: order.totalAmountPaise }}/></div><div className="mt-4 grid gap-3">{order.status === 'PENDING' ? <><Button disabled={busy} onClick={() => void transition('ACCEPTED')}>Accept order</Button><Button variant="ghost" disabled={busy} className="text-red-700" onClick={() => void transition('REJECTED')}>Reject order</Button></> : null}{target && order.status !== 'PENDING' && !(target === 'COMPLETED' && order.paymentStatus !== 'PAID') ? <Button disabled={busy} onClick={() => void transition(target)}>{actionLabels[target]}</Button> : null}{order.status === 'READY' && order.paymentStatus === 'PENDING' ? <Button variant="secondary" disabled={busy} onClick={() => void markPaid()}>Confirm cash collected</Button> : null}{order.status === 'READY' && order.paymentStatus === 'PENDING' ? <p className="text-xs text-stone-500">Collect and confirm cash before completing this order.</p> : null}</div></aside></div>
  </section>;
}
