import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { SellerOrderWorkspace } from './seller-order-workspace';

const mocks = vi.hoisted(() => ({ listSellerOrders: vi.fn(), getSellerOrder: vi.fn(), getSellerOrderSummary: vi.fn(), changeSellerOrderStatus: vi.fn(), markSellerOrderPaid: vi.fn() }));
vi.mock('@/services/order-service', () => mocks);
const item = { id: 'order-item-1', menuItemId: 'menu-1', itemName: 'Dosa', pricePaise: 8500, quantity: 2, veg: true, bestseller: false, itemTotalPaise: 17000 };
const order = { id: 'order-1', orderNumber: 'CB-2026-ABC123', userId: 'user-1', userName: 'Student One', userPhone: '+919999999999', sellerId: 'seller-1', sellerName: 'Campus Foods', hotelId: 'hotel-1', hotelName: 'Campus Cafe', hotelPhone: '+918888888888', universityId: 'university-1', subtotalPaise: 17000, deliveryChargePaise: 0, platformFeePaise: 0, totalAmountPaise: 17000, orderType: 'INSTANT', deliveryType: 'PICKUP', deliveryAddress: null, scheduledAt: null, paymentMethod: 'CASH', paymentStatus: 'PENDING', status: 'PENDING', createdAt: '2026-08-21T06:30:00Z', updatedAt: '2026-08-21T06:30:00Z', items: [item], statusHistory: [{ id: 'history-1', fromStatus: null, toStatus: 'PENDING', changedById: 'user-1', createdAt: '2026-08-21T06:30:00Z' }] };
const summary = { statusCounts: { PENDING: 1, ACCEPTED: 0, PREPARING: 0, READY: 0, COMPLETED: 0, REJECTED: 0, CANCELLED: 0 }, todayOrders: 1, todaySalesPaise: 0, todayCompletedOrders: 0, businessDate: '2026-08-21' };
describe('SellerOrderWorkspace', () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.listSellerOrders.mockResolvedValue({ orders: [order], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } }); mocks.getSellerOrderSummary.mockResolvedValue(summary); mocks.getSellerOrder.mockResolvedValue({ order }); mocks.changeSellerOrderStatus.mockResolvedValue({ order: { ...order, status: 'ACCEPTED' } }); vi.stubGlobal('confirm', vi.fn(() => true)); });
  it('renders dashboard metrics and the private order queue', async () => { render(<SellerOrderWorkspace />); expect(await screen.findByText('CB-2026-ABC123')).toBeInTheDocument(); expect(screen.getByText('Student One')).toBeInTheDocument(); expect(screen.getByText("Today's paid sales")).toBeInTheDocument(); expect(screen.getByText('₹0.00')).toBeInTheDocument(); });
  it('opens full snapshots and accepts a pending order', async () => { render(<SellerOrderWorkspace />); fireEvent.click(await screen.findByRole('button', { name: /CB-2026-ABC123/ })); expect(await screen.findByText('Order from Student One')).toBeInTheDocument(); expect(screen.getByText('2 × Dosa')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Accept order' })); await waitFor(() => expect(mocks.changeSellerOrderStatus).toHaveBeenCalledWith('order-1', 'ACCEPTED')); });
  it('collects cash on a ready order before showing completion', async () => { const ready = { ...order, status: 'READY', paymentStatus: 'PENDING' }; mocks.listSellerOrders.mockResolvedValue({ orders: [ready], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } }); mocks.getSellerOrder.mockResolvedValue({ order: ready }); mocks.markSellerOrderPaid.mockResolvedValue({ order: { ...ready, paymentStatus: 'PAID' } }); render(<SellerOrderWorkspace />); fireEvent.click(await screen.findByRole('button', { name: /CB-2026-ABC123/ })); fireEvent.click(await screen.findByRole('button', { name: 'Confirm cash collected' })); await waitFor(() => expect(mocks.markSellerOrderPaid).toHaveBeenCalledWith('order-1')); expect(window.confirm).toHaveBeenCalled(); });
  it('shows an empty filtered state and recoverable load error', async () => { mocks.listSellerOrders.mockResolvedValueOnce({ orders: [], pagination: { page: 1, limit: 20, total: 0, totalPages: 0 } }); const view = render(<SellerOrderWorkspace />); expect(await screen.findByText('No matching orders')).toBeInTheDocument(); view.unmount(); mocks.listSellerOrders.mockRejectedValue(new Error('network')); render(<SellerOrderWorkspace />); expect(await screen.findByText('Orders could not be loaded.')).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Try again' })).toBeInTheDocument(); });
});
