'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { Alert } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { ApiClientError } from '@/services/api-client';
import { previewCart } from '@/services/cart-service';
import type { CartPreview } from '@/types/cart';
import { formatInr } from '@/utils/money';
import { CART_MAX_QUANTITY, useCart } from './cart-context';

export function CartPage() {
  const cart = useCart(); const [preview, setPreview] = useState<CartPreview | null>(null); const [status, setStatus] = useState<'idle' | 'loading' | 'ready' | 'error'>('idle'); const [message, setMessage] = useState('');
  const validate = useCallback(async () => { if (!cart.hydrated || !cart.items.length) { setPreview(null); setStatus('idle'); return; } setStatus('loading'); try { const result = await previewCart(cart.items); setPreview(result); setStatus('ready'); const authoritative = result.items.map((item) => ({ menuItemId: item.menuItemId, hotelId: item.hotelId, hotelName: result.hotel.hotelName, itemName: item.itemName, pricePaise: item.pricePaise, quantity: item.quantity, veg: item.veg, bestseller: item.bestseller })); if (JSON.stringify(authoritative) !== JSON.stringify(cart.items)) cart.reconcile(authoritative); } catch (error) { setMessage(error instanceof ApiClientError ? error.message : 'Your cart could not be validated.'); setStatus('error'); } }, [cart]);
  useEffect(() => { const timer = setTimeout(() => void validate(), 150); return () => clearTimeout(timer); }, [validate]);
  if (!cart.hydrated) return <div role="status" className="mt-8 rounded-3xl border bg-white p-10 text-center">Loading your cart…</div>;
  if (!cart.items.length) return <section className="mt-8 rounded-3xl border border-dashed border-stone-300 bg-white p-10 text-center"><h2 className="text-2xl font-bold">Your cart is empty</h2><p className="mt-2 text-stone-500">Browse a campus outlet and add something delicious.</p><Link href="/user" className="mt-5 inline-flex rounded-xl bg-brand-orange-500 px-5 py-3 font-semibold text-white">Explore outlets</Link></section>;
  const totals = preview?.totals ?? { totalQuantity: cart.totalQuantity, itemsTotalPaise: cart.itemsTotalPaise, deliveryChargePaise: 0, platformFeePaise: 0, grandTotalPaise: cart.itemsTotalPaise };
  return <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]">
    <section className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand-green-500">One outlet</p><h2 className="mt-2 text-2xl font-bold">{cart.items[0]!.hotelName}</h2></div><Button variant="ghost" onClick={() => { if (confirm('Clear every item from your cart?')) cart.clear(); }}>Clear cart</Button></div>{status === 'loading' ? <p role="status" className="mt-5 text-sm text-stone-500">Checking current prices and availability…</p> : null}{status === 'error' ? <div className="mt-5"><Alert>{message}</Alert><Button variant="ghost" className="mt-3" onClick={() => void validate()}>Try again</Button></div> : null}{preview?.issues.map((issue) => <div className="mt-5" key={issue.code}><Alert>{issue.message}</Alert></div>)}<div className="mt-6 divide-y divide-stone-200">{cart.items.map((item) => { const unavailable = preview?.items.find((value) => value.menuItemId === item.menuItemId)?.available === false; return <article key={item.menuItemId} className={`py-5 first:pt-0 ${unavailable ? 'opacity-60' : ''}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><span className={`size-3 rounded-full ${item.veg ? 'bg-green-600' : 'bg-red-600'}`} /><h3 className="font-bold">{item.itemName}</h3>{unavailable ? <span className="rounded-full bg-red-100 px-2 py-1 text-xs font-bold text-red-700">Unavailable</span> : null}</div><p className="mt-2 text-sm text-stone-500">{formatInr(item.pricePaise)} each · <strong>{formatInr(item.pricePaise * item.quantity)}</strong></p></div><div className="flex items-center gap-2"><Button variant="ghost" aria-label={`Decrease ${item.itemName}`} className="min-h-10 px-4" onClick={() => cart.decrease(item.menuItemId)}>−</Button><span className="min-w-8 text-center font-bold">{item.quantity}</span><Button variant="ghost" aria-label={`Increase ${item.itemName}`} className="min-h-10 px-4" disabled={item.quantity >= CART_MAX_QUANTITY} onClick={() => cart.increase(item.menuItemId)}>+</Button><Button variant="ghost" className="min-h-10 px-3 text-red-700" onClick={() => cart.remove(item.menuItemId)}>Remove</Button></div></div></article>; })}</div></section>
    <aside className="h-fit rounded-3xl border border-stone-200 bg-white p-6 shadow-sm lg:sticky lg:top-24"><h2 className="text-xl font-bold">Price summary</h2><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><dt>Items ({totals.totalQuantity})</dt><dd>{formatInr(totals.itemsTotalPaise)}</dd></div><div className="flex justify-between"><dt>Delivery charge</dt><dd>{formatInr(totals.deliveryChargePaise)}</dd></div><div className="flex justify-between"><dt>Platform fee</dt><dd>{formatInr(totals.platformFeePaise)}</dd></div><div className="flex justify-between border-t border-stone-200 pt-4 text-base font-bold"><dt>Grand total</dt><dd>{formatInr(totals.grandTotalPaise)}</dd></div></dl>{status === 'ready' && preview?.orderable ? <Link href="/user/checkout" className="mt-6 flex min-h-11 w-full items-center justify-center rounded-xl bg-brand-orange-500 px-5 py-2.5 text-sm font-semibold text-white shadow-sm">Proceed to checkout</Link> : <Button className="mt-6 w-full" disabled>Proceed to checkout</Button>}<p className="mt-3 text-xs leading-5 text-stone-500">Prices and availability are verified by CampusBites before checkout.</p></aside>
  </div>;
}
