import { HotelStatus, Prisma } from '@prisma/client';
import { AppError } from '../errors/app-error.js';
import * as hotelRepository from '../repositories/hotel.repository.js';
import * as repository from '../repositories/menu.repository.js';

export type MenuInput = { name?: string; description?: string | null; pricePaise?: number; category?: string; veg?: boolean; bestseller?: boolean; preparationTimeMinutes?: number; available?: boolean; displayOrder?: number };
const clean = (value: string) => value.trim().replace(/\s+/g, ' ');
function cleanInput(input: MenuInput) { return { ...(input.name === undefined ? {} : { name: clean(input.name) }), ...(input.description === undefined ? {} : { description: input.description === null || input.description.trim() === '' ? null : clean(input.description) }), ...(input.pricePaise === undefined ? {} : { pricePaise: input.pricePaise }), ...(input.category === undefined ? {} : { category: input.category }), ...(input.veg === undefined ? {} : { veg: input.veg }), ...(input.bestseller === undefined ? {} : { bestseller: input.bestseller }), ...(input.preparationTimeMinutes === undefined ? {} : { preparationTimeMinutes: input.preparationTimeMinutes }), ...(input.available === undefined ? {} : { available: input.available }), ...(input.displayOrder === undefined ? {} : { displayOrder: input.displayOrder }) }; }
function paginate<T>(items: T[], total: number, page: number, limit: number) { return { menuItems: items, pagination: { page, limit, total, totalPages: Math.ceil(total / limit), hasNextPage: page * limit < total, hasPreviousPage: page > 1 } }; }
function mapWriteError(error: unknown): never { if (error instanceof Prisma.PrismaClientKnownRequestError) { if (error.code === 'P2002') throw new AppError(409, 'MENU_ITEM_ALREADY_EXISTS', 'An item with this name already exists in the outlet menu'); if (error.code === 'P2025') throw new AppError(404, 'MENU_ITEM_NOT_FOUND', 'Menu item was not found'); if (error.code === 'P2003') throw new AppError(409, 'MENU_ITEM_IN_USE', 'This item is referenced by order history and cannot be deleted'); } throw error; }
async function sellerHotel(sellerId: string, requireApproved: boolean) { const hotel = await hotelRepository.findBySellerId(sellerId); if (!hotel) throw new AppError(409, 'SELLER_HOTEL_REQUIRED', 'Create a food outlet before managing a menu'); if (requireApproved && (hotel.status !== HotelStatus.APPROVED || !hotel.active)) throw new AppError(409, 'APPROVED_HOTEL_REQUIRED', 'Only an active approved outlet can publish menu items'); return hotel; }
async function ownedItem(sellerId: string, id: string) { const item = await repository.findById(id); if (!item) throw new AppError(404, 'MENU_ITEM_NOT_FOUND', 'Menu item was not found'); if (item.hotel.sellerId !== sellerId) throw new AppError(403, 'MENU_ITEM_OWNERSHIP_REQUIRED', 'You can manage only your own outlet menu'); if (item.hotel.status !== HotelStatus.APPROVED || !item.hotel.active) throw new AppError(409, 'APPROVED_HOTEL_REQUIRED', 'Only an active approved outlet can publish menu items'); return item; }

export async function listPublicMenu(hotelId: string, filters: repository.MenuFilters) { const hotel = await hotelRepository.findPublicById(hotelId); if (!hotel || hotel.status !== HotelStatus.APPROVED || !hotel.active || !hotel.university.active) throw new AppError(404, 'HOTEL_NOT_FOUND', 'Approved food outlet was not found'); const result = await repository.list(hotelId, filters); return { hotel, ...paginate(result.items, result.total, filters.page, filters.limit) }; }
export async function listSellerMenu(sellerId: string, filters: repository.MenuFilters) { const hotel = await sellerHotel(sellerId, false); const result = await repository.list(hotel.id, filters); return { hotel, ...paginate(result.items, result.total, filters.page, filters.limit) }; }
export async function createMenuItem(sellerId: string, input: Required<Omit<MenuInput, 'description' | 'displayOrder'>> & Pick<MenuInput, 'description' | 'displayOrder'>) { const hotel = await sellerHotel(sellerId, true); try { return await repository.create({ ...cleanInput(input) as Prisma.MenuItemUncheckedCreateInput, hotelId: hotel.id, displayOrder: input.displayOrder ?? await repository.nextDisplayOrder(hotel.id) }); } catch (error) { mapWriteError(error); } }
export async function updateMenuItem(sellerId: string, id: string, input: MenuInput) { await ownedItem(sellerId, id); try { return await repository.update(id, cleanInput(input)); } catch (error) { mapWriteError(error); } }
export async function setAvailability(sellerId: string, id: string, available: boolean) { return updateMenuItem(sellerId, id, { available }); }
export async function setBestseller(sellerId: string, id: string, bestseller: boolean) { return updateMenuItem(sellerId, id, { bestseller }); }
export async function deleteMenuItem(sellerId: string, id: string) { await ownedItem(sellerId, id); try { await repository.remove(id); } catch (error) { mapWriteError(error); } }
export async function reorderMenu(sellerId: string, items: { id: string; displayOrder: number }[]) { const hotel = await sellerHotel(sellerId, true); const owned = await repository.findOwnedIds(hotel.id, items.map((item) => item.id)); if (owned.length !== items.length) throw new AppError(403, 'MENU_ITEM_OWNERSHIP_REQUIRED', 'Every reordered item must belong to your outlet'); return repository.reorder(items); }
